[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"

[fuzz]
# seed = "0x01"
runs = 1000

[invariant]
# seed = "0x01"
runs = 128
depth = 128
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
